export type Shipment = {
		data: {
			account: {
				account_code: string;
				account_type: string;
				balance: number;
				branch_id: number;
				branch_name: string | null;
				charge_discrepancy_threshold_override: number;
				created_by: number;
				credit_allocation_balance: number;
				current_rate_group_id: number;
				current_rate_group_name: string;
				// biome-ignore lint/suspicious/noExplicitAny: <explanation>
				custom_fields: any | null;
				default_collection_address_id: number;
				disable_auto_hold: boolean;
				disable_driver_app_notification_email: boolean;
				disable_driver_app_notification_sms: boolean;
				disable_out_for_delivery_email: boolean;
				disable_out_for_delivery_sms: boolean;
				force_show_billing_transactions: boolean;
				id: number;
				include_unencrypted_pod_pin: boolean;
				invoice_allocation_method: string;
				invoice_frequency: string;
				invoice_frequency_time: number;
				invoice_trigger_shipment_status: null;
				is_on_hold: boolean;
				name: string;
				override_tracking_prefixes: boolean;
				pod_method: string;
				pod_method_visible_on_shipment: boolean;
				provider_id: number;
				status: string;
				support_email: string;
				temp_disable_auto_hold: boolean;
				time_created: string;
				time_modified: string;
				tracking_prefix: string;
				trading_start_date: string;
				vat_number: string;
			};
			created_by: number;
			id: number;
			rate: number;
			rating_reference: string;
			responsible_contact_id: number;
			service_level_code: string;
			service_level_cut_off_time: string;
			service_level_id: number;
			service_level_name: string;
			short_tracking_reference: string;
			source: string;
			special_instructions_collection: string;
			special_instructions_delivery: string;
			status: string;
			time_created: string;
			time_modified: string;
			total_note_count: number;
			tracking_events: null;
			transient_branch_ids: null;
			volumetric_weight: number;
		};
	};
