import Navbar from '@/components/Layout/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import SupabaseProvider from '@/Providers/SupabaseProvider'
import { createClient } from '@supabase/supabase-js'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

    const supabase = createServerComponentClient({ cookies });

   const {
     data: { session },
   } = await supabase.auth.getSession();

   const {
     data: { user },
   } = await supabase.auth.getUser();

   let { data: admin, error } = await supabase.rpc("is_admin");




  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <Navbar user={user} />
          {children}
        </SupabaseProvider>
      </body>
    </html>
  );
}
